# Develop profile (don't communicate with services, only send information to console)
spring.config.activate.on-profile=develop
# Telegram_develop
tg.username=vbeznosov_job4j_bot
tg.token=8763278347:AAGmvpy_4nwkNkdSqw52gD87j4O12H71Pb0
